## Importing Packages

In [13]:
import pandas as pd
import numpy as np
from datetime import datetime

## Uploading Data

In [2]:
candy_raw = pd.read_excel(r"C:\Users\datre\OneDrive\Documents\Graduate School\Summer '20\candyhierarchy2017.xlsx")
candy_raw.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

In [3]:
candy_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB

In [4]:
# Ch. 7: 1
candy_raw.drop_duplicates(subset = "Internal ID", keep = False, inplace = True)
candy_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB

There were no duplicates to drop

In [5]:
# Ch. 7:2
HGB = candy_raw["Q6 | 100 Grand Bar"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
CC = candy_raw["Q6 | Candy Corn"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
HMC = candy_raw["Q6 | Hersheyâ€™s Milk Chocolate"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
LP = candy_raw["Q6 | Lollipops"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
BC = candy_raw["Q6 | Bottle Caps"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
BF = candy_raw["Q6 | Butterfinger"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
DOT = candy_raw["Q6 | Dots"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
GB = candy_raw["Q6 | Gummy Bears straight up"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
HK = candy_raw["Q6 | Hershey's Kisses"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
JM = candy_raw["Q6 | Junior Mints"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
KK = candy_raw["Q6 | Kit Kat"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
LT = candy_raw["Q6 | LaffyTaffy"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
MD = candy_raw["Q6 | Milk Duds"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
MW = candy_raw["Q6 | Milky Way"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
NC = candy_raw["Q6 | Nestle Crunch"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
PSTX = candy_raw["Q6 | Pixy Stix"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
RC = candy_raw["Q6 | Reeseâ€™s Peanut Butter Cups"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
RCP = candy_raw["Q6 | Reese's Pieces"].map(dict(DESPAIR = 1, MEH = 2, JOY = 3))
data = [HGB, CC, HMC, LP, BC, BF, DOT, GB, HK, JM, KK, LT, MD, MW, NC, PSTX, RC, RCP]
candy_df = pd.DataFrame(data)
candy_df

,0,1,2,3,4,5,6,7,8,9,...,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459
Q6 | 100 Grand Bar,NaN,2.0,NaN,2.0,3.0,3.0,NaN,3.0,3.0,2.0,...,NaN,NaN,3.0,2.0,3.0,3.0,2.0,2.0,NaN,1.0
Q6 | Candy Corn,NaN,2.0,NaN,1.0,1.0,2.0,NaN,3.0,1.0,2.0,...,NaN,NaN,2.0,1.0,3.0,1.0,3.0,1.0,NaN,2.0
Q6 | Hersheyâ€™s Milk Chocolate,NaN,3.0,NaN,2.0,2.0,2.0,NaN,2.0,3.0,2.0,...,NaN,NaN,2.0,1.0,3.0,2.0,3.0,3.0,NaN,3.0
Q6 | Lollipops,NaN,1.0,NaN,1.0,2.0,2.0,NaN,2.0,2.0,2.0,...,NaN,NaN,2.0,3.0,2.0,1.0,2.0,2.0,NaN,1.0
Q6 | Bottle Caps,NaN,1.0,NaN,2.0,2.0,2.0,NaN,3.0,2.0,2.0,...,NaN,NaN,3.0,2.0,2.0,2.0,NaN,1.0,NaN,1.0
Q6 | Butterfinger,NaN,1.0,NaN,2.0,2.0,3.0,NaN,3.0,3.0,2.0,...,NaN,NaN,3.0,3.0,3.0,2.0,3.0,1.0,NaN,3.0
Q6 | Dots,NaN,2.0,NaN,3.0,2.0,2.0,NaN,2.0,1.0,2.0,...,NaN,NaN,1.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0
Q6 | Gummy Bears straight up,NaN,2.0,NaN,3.0,3.0,2.0,NaN,3.0,1.0,2.0,...,NaN,NaN,2.0,1.0,3.0,2.0,2.0,2.0,NaN,2.0
Q6 | Hershey's Kisses,NaN,2.0,NaN,2.0,2.0,2.0,NaN,2.0,3.0,2.0,...,NaN,NaN,2.0,1.0,3.0,2.0,2.0,3.0,NaN,3.0
Q6 | Junior Mints,NaN,1.0,NaN,1.0,3.0,3.0,NaN,1.0,2.0,3.0,...,NaN,NaN,1.0,3.0,3.0,1.0,3.0,3.0,NaN,3.0
Q6 | Kit Kat,NaN,3.0,NaN,2.0,3.0,3.0,NaN,2.0,3.0,3.0,...,NaN,NaN,3.0,3.0,3.0,3.0,3.0,1.0,NaN,2.0
Q6 | LaffyTaffy,NaN,1.0,NaN,3.0,3.0,2.0,NaN,2.0,2.0,1.0,...,NaN,NaN,2.0,2.0,1.0,2.0,1.0,3.0,NaN,1.0
Q6 | Milk Duds,NaN,2.0,NaN,1.0,2.0,3.0,NaN,3.0,3.0,2.0,...,NaN,NaN,3.0,1.0,3.0,3.0,2.0,3.0,NaN,1.0
Q6 | Milky Way,NaN,3.0,NaN,3.0,3.0,3.0,NaN,3.0,3.0,2.0,...,NaN,NaN,3.0,3.0,3.0,3.0,2.0,3.0,NaN,3.0
Q6 | Nestle Crunch,NaN,3.0,NaN,2.0,3.0,2.0,NaN,3.0,3.0,2.0,...,NaN,NaN,3.0,3.0,3.0,3.0,2.0,1.0,NaN,2.0
Q6 | Pixy Stix,NaN,1.0,NaN,1.0,3.0,2.0,NaN,1.0,1.0,1.0,...,NaN,NaN,2.0,NaN,2.0,3.0,2.0,3.0,NaN,1.0
Q6 | Reeseâ€™s Peanut Butter Cups,NaN,3.0,NaN,3.0,3.0,3.0,NaN,3.0,3.0,3.0,...,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,NaN,2.0
Q6 | Reese's Pieces,NaN,3.0,NaN,2.0,3.0,3.0,NaN,3.0,3.0,3.0,...,NaN,NaN,3.0,3.0,3.0,3.0,3.0,2.0,NaN,1.0

In [6]:
# Ch. 8: 1
stack = candy_df.stack().to_frame()
stack

                            0
Q6 | 100 Grand Bar  1     2.0
                    3     2.0
                    4     3.0
                    5     3.0
                    7     3.0
...                       ...
Q6 | Reese's Pieces 2454  3.0
                    2455  3.0
                    2456  3.0
                    2457  2.0
                    2459  1.0

[31662 rows x 1 columns]

In [7]:
HGB = candy_raw["Q6 | 100 Grand Bar"]
CC = candy_raw["Q6 | Candy Corn"]
HMC = candy_raw["Q6 | Hersheyâ€™s Milk Chocolate"]
LP = candy_raw["Q6 | Lollipops"]
BC = candy_raw["Q6 | Bottle Caps"]
BF = candy_raw["Q6 | Butterfinger"]
DOT = candy_raw["Q6 | Dots"]
GB = candy_raw["Q6 | Gummy Bears straight up"]
HK = candy_raw["Q6 | Hershey's Kisses"]
JM = candy_raw["Q6 | Junior Mints"]
KK = candy_raw["Q6 | Kit Kat"]
LT = candy_raw["Q6 | LaffyTaffy"]
MD = candy_raw["Q6 | Milk Duds"]
MW = candy_raw["Q6 | Milky Way"]
NC = candy_raw["Q6 | Nestle Crunch"]
PSTX = candy_raw["Q6 | Pixy Stix"]
RC = candy_raw["Q6 | Reeseâ€™s Peanut Butter Cups"]
RCP = candy_raw["Q6 | Reese's Pieces"]
AGE = candy_raw["Q3: AGE"]
data = [AGE, HGB, CC, HMC, LP, BC, BF, DOT, GB, HK, JM, KK, LT, MD, MW, NC, PSTX, RC, RCP]
candy_df2 = pd.DataFrame(data)
candy_df2

,0,1,2,3,4,5,6,7,8,9,...,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459
Q3: AGE,NaN,44,49.0,40,23,NaN,53.0,33,40,53,...,NaN,25.0,43,40,26,24,33,26,58.0,66
Q6 | 100 Grand Bar,NaN,MEH,NaN,MEH,JOY,JOY,NaN,JOY,JOY,MEH,...,NaN,NaN,JOY,MEH,JOY,JOY,MEH,MEH,NaN,DESPAIR
Q6 | Candy Corn,NaN,MEH,NaN,DESPAIR,DESPAIR,MEH,NaN,JOY,DESPAIR,MEH,...,NaN,NaN,MEH,DESPAIR,JOY,DESPAIR,JOY,DESPAIR,NaN,MEH
Q6 | Hersheyâ€™s Milk Chocolate,NaN,JOY,NaN,MEH,MEH,MEH,NaN,MEH,JOY,MEH,...,NaN,NaN,MEH,DESPAIR,JOY,MEH,JOY,JOY,NaN,JOY
Q6 | Lollipops,NaN,DESPAIR,NaN,DESPAIR,MEH,MEH,NaN,MEH,MEH,MEH,...,NaN,NaN,MEH,JOY,MEH,DESPAIR,MEH,MEH,NaN,DESPAIR
Q6 | Bottle Caps,NaN,DESPAIR,NaN,MEH,MEH,MEH,NaN,JOY,MEH,MEH,...,NaN,NaN,JOY,MEH,MEH,MEH,NaN,DESPAIR,NaN,DESPAIR
Q6 | Butterfinger,NaN,DESPAIR,NaN,MEH,MEH,JOY,NaN,JOY,JOY,MEH,...,NaN,NaN,JOY,JOY,JOY,MEH,JOY,DESPAIR,NaN,JOY
Q6 | Dots,NaN,MEH,NaN,JOY,MEH,MEH,NaN,MEH,DESPAIR,MEH,...,NaN,NaN,DESPAIR,MEH,MEH,DESPAIR,DESPAIR,MEH,NaN,JOY
Q6 | Gummy Bears straight up,NaN,MEH,NaN,JOY,JOY,MEH,NaN,JOY,DESPAIR,MEH,...,NaN,NaN,MEH,DESPAIR,JOY,MEH,MEH,MEH,NaN,MEH
Q6 | Hershey's Kisses,NaN,MEH,NaN,MEH,MEH,MEH,NaN,MEH,JOY,MEH,...,NaN,NaN,MEH,DESPAIR,JOY,MEH,MEH,JOY,NaN,JOY
Q6 | Junior Mints,NaN,DESPAIR,NaN,DESPAIR,JOY,JOY,NaN,DESPAIR,MEH,JOY,...,NaN,NaN,DESPAIR,JOY,JOY,DESPAIR,JOY,JOY,NaN,JOY
Q6 | Kit Kat,NaN,JOY,NaN,MEH,JOY,JOY,NaN,MEH,JOY,JOY,...,NaN,NaN,JOY,JOY,JOY,JOY,JOY,DESPAIR,NaN,MEH
Q6 | LaffyTaffy,NaN,DESPAIR,NaN,JOY,JOY,MEH,NaN,MEH,MEH,DESPAIR,...,NaN,NaN,MEH,MEH,DESPAIR,MEH,DESPAIR,JOY,NaN,DESPAIR
Q6 | Milk Duds,NaN,MEH,NaN,DESPAIR,MEH,JOY,NaN,JOY,JOY,MEH,...,NaN,NaN,JOY,DESPAIR,JOY,JOY,MEH,JOY,NaN,DESPAIR
Q6 | Milky Way,NaN,JOY,NaN,JOY,JOY,JOY,NaN,JOY,JOY,MEH,...,NaN,NaN,JOY,JOY,JOY,JOY,MEH,JOY,NaN,JOY
Q6 | Nestle Crunch,NaN,JOY,NaN,MEH,JOY,MEH,NaN,JOY,JOY,MEH,...,NaN,NaN,JOY,JOY,JOY,JOY,MEH,DESPAIR,NaN,MEH
Q6 | Pixy Stix,NaN,DESPAIR,NaN,DESPAIR,JOY,MEH,NaN,DESPAIR,DESPAIR,DESPAIR,...,NaN,NaN,MEH,NaN,MEH,JOY,MEH,JOY,NaN,DESPAIR
Q6 | Reeseâ€™s Peanut Butter Cups,NaN,JOY,NaN,JOY,JOY,JOY,NaN,JOY,JOY,JOY,...,NaN,NaN,JOY,JOY,JOY,JOY,JOY,JOY,NaN,MEH
Q6 | Reese's Pieces,NaN,JOY,NaN,MEH,JOY,JOY,NaN,JOY,JOY,JOY,...,NaN,NaN,JOY,JOY,JOY,JOY,JOY,MEH,NaN,DESPAIR

In [8]:
df = pd.DataFrame({'key1' : ["Dark Choc", "Dark Choc", "Dark Choc", "Milk Choc", "Milk Choc", "Milk Choc"],
                  'key2' : ["Despair", "Meh", "Joy", "Despair", "Meh", "Joy"],
                  'data1' : [6,21,44,9,31,30],
                  'data2' : [9,17,44,10,30,29]})
df

        key1     key2  data1  data2
0  Dark Choc  Despair      6      9
1  Dark Choc      Meh     21     17
2  Dark Choc      Joy     44     44
3  Milk Choc  Despair      9     10
4  Milk Choc      Meh     31     30
5  Milk Choc      Joy     30     29

In [9]:
# Ch. 10: 1
grouped1 = df['data1'].groupby(df['key1'])
grouped1.mean()

key1
Dark Choc    23.666667
Milk Choc    23.333333
Name: data1, dtype: float64

In [10]:
# Ch. 10: 1
grouped2 = df['data1'].groupby(df['key2'])
grouped2.mean()

key2
Despair     7.5
Joy        37.0
Meh        26.0
Name: data1, dtype: float64

In [11]:
# Ch. 10: 2
candy_corn = pd.crosstab(candy_raw["Q3: AGE"], candy_raw["Q6 | Candy Corn"], margins = True)
candy_corn

Q6 | Candy Corn  DESPAIR  JOY  MEH   All
Q3: AGE
4                      0    1    0     1
6                      0    1    0     1
7                      1    0    0     1
8                      0    2    0     2
9                      0    2    1     3
...                  ...  ...  ...   ...
no                     1    0    0     1
old                    1    0    0     1
old enough             0    0    1     1
older than dirt        1    0    0     1
All                  729  469  550  1748

[99 rows x 4 columns]

In [16]:
candy_time = pd.read_excel(r"C:\Users\datre\OneDrive\Documents\Graduate School\Summer '20\BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx")
candy_time.head()

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [BeyoncÃ©],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

In [31]:
candy_time.dtypes

Timestamp                                                                                                                                    datetime64[ns]
Are you going actually going trick or treating yourself?                                                                                             object
Your gender:                                                                                                                                         object
How old are you?                                                                                                                                     object
Which country do you live in?                                                                                                                        object
                                                                                                                                                  ...
Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                                    object
Which day do you prefer, Friday or Sunday?                                                                                                           object
Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?            object
When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).                              object
 [York Peppermint Patties] Ignore                                                                                                                   float64
Length: 123, dtype: object

In [15]:
now = datetime.now()
now.year

2020

In [21]:
#Ch. 11: 1
index = pd.date_range("2016-10-24","2016-12-24")

In [32]:
#Ch. 11: 2
(candy_time.Timestamp.max()-candy_time.Timestamp.min()).days

6

In [33]:
#Ch. 11: 2
candy_time.Timestamp.max(), candy_time.Timestamp.min()

(Timestamp('2016-10-30 17:06:45.660000'),
 Timestamp('2016-10-24 05:09:23.033000'))